// <copyright file="Program.cs" company="PublicDomain.com">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />

namespace Enfolder
{
    // Directives
    using System;
    using System.IO;
    using System.IO.Pipes;
    using System.Reflection;
    using System.Threading;
    using System.Windows.Forms;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO.MemoryMappedFiles;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Linq;

    /// <summary>
    /// Class with program entry point.
    /// </summary>
    internal sealed class Program
    {
        /// <summary>
        /// The mutex.
        /// </summary>
        private static Mutex mutex = null;

        /// <summary>
        /// The file path.
        /// </summary>
        private static string filePath = "EnfolderItems.txt";

        /// <summary>
        /// Program entry point.
        /// </summary>
        [STAThread]
        private static void Main(string[] args)
        {
            // Check arguments for context menu start
            if (args.Length > 0)
            {
                // The first instance flag
                bool firstInstance;

                // Set items
                var items = new List<string>(args).GetRange(1, args.Length - 1);

                // Set mutext
                mutex = new Mutex(true, @"Local\Enfolder", out firstInstance);

                // Set written flag
                bool written = false;

                // Append to item file
                while (!written)
                {
                    try
                    {
                        // Append items
                        File.AppendAllLines(filePath, items);
                    }
                    catch
                    {
                        Thread.Sleep(20);
                    }
                }

                // Check for first instance
                if (firstInstance)
                {
                    // First instance
                    try
                    {
                        // Launch enfolder form
                        Application.EnableVisualStyles();
                        Application.SetCompatibleTextRenderingDefault(false);
                        Application.Run(new EnfolderForm());
                    }
                    finally
                    {
                        // Release the mutex
                        mutex.ReleaseMutex();
                    }
                }
            }
            else // By user
            {
                // Run main form
                Application.EnableVisualStyles();
                Application.SetCompatibleTextRenderingDefault(false);
                Application.Run(new MainForm());
            }
        }
    }
}
